"""Builds dist/index.html (home) and dist/arcade.html (/arcade) from tools/site/layout.html + home.html / arcade.html.

Single sources of truth:
  tools/site/site.json   official links (website / X / Telegram) + Arcade game metadata
  tools/site/icons.json  pixel icons (generated by tools/site/icons.py)

Outputs:
  dist/index.html        page with socials + game cards rendered from site.json
  dist/site-config.js    window.HALLOWINU_SITE for runtime JS (arcade.js)
  worker/site-meta.js    the same data for the Worker (X handle, game names)
"""
import json, re, random, html, os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
P = lambda *a: os.path.join(ROOT, *a)
V = '45'

icons = json.load(open(P('tools/site/icons.json')))
site = json.load(open(P('tools/site/site.json')))
L = site['links']
for k in ('website', 'x', 'telegram', 'xHandle'):
    assert L.get(k), f'site.json links.{k} missing'
for g in site['games']:
    assert g['icon'] in icons, f"unknown icon {g['icon']} for {g['id']}"

TG = '<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path fill="currentColor" d="M21.9 4.3 18.7 19.4c-.2 1.1-.9 1.3-1.8.8l-4.9-3.6-2.4 2.3c-.3.3-.5.5-1 .5l.3-5 9.2-8.3c.4-.4-.1-.6-.6-.2L6.1 13 1.2 11.5c-1.1-.3-1.1-1.1.2-1.6L20.6 2.5c.9-.3 1.7.2 1.3 1.8Z"/></svg>'
X = '<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path fill="currentColor" d="M17.8 2.5h3.3l-7.2 8.2 8.5 10.8h-6.6l-5.2-6.8-6 6.8H1.3l7.7-8.8L.9 2.5h6.8l4.7 6.2 5.4-6.2Zm-1.2 17.1h1.8L6.6 4.3H4.6l12 15.3Z"/></svg>'
WEB = '<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path fill="currentColor" d="M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Zm6.9 6h-3a15.6 15.6 0 0 0-1.4-3.6A8 8 0 0 1 18.9 8ZM12 4.1c.8 1.1 1.5 2.4 1.9 3.9h-3.8c.4-1.5 1.1-2.8 1.9-3.9ZM4.3 14a8.2 8.2 0 0 1 0-4h3.4a16.5 16.5 0 0 0 0 4H4.3Zm.8 2h3a15.6 15.6 0 0 0 1.4 3.6A8 8 0 0 1 5.1 16Zm3-8h-3a8 8 0 0 1 4.4-3.6A15.6 15.6 0 0 0 8.1 8ZM12 19.9c-.8-1.1-1.5-2.4-1.9-3.9h3.8c-.4 1.5-1.1 2.8-1.9 3.9Zm2.3-5.9H9.7a14.7 14.7 0 0 1 0-4h4.6a14.7 14.7 0 0 1 0 4Zm.2 5.6c.6-1.1 1.1-2.3 1.4-3.6h3a8 8 0 0 1-4.4 3.6Zm1.8-5.6a16.5 16.5 0 0 0 0-4h3.4a8.2 8.2 0 0 1 0 4h-3.4Z"/></svg>'
symbols = ''
for k, v in icons.items():
    inner = re.sub(r'^<svg[^>]*>|</svg>$', '', v)
    vb = re.search(r'viewBox="([^"]+)"', v).group(1)
    symbols += f'<symbol id="i-{k}" viewBox="{vb}">{inner}</symbol>'

for k, svg in (('x', X), ('tg', TG), ('web', WEB)):
    symbols += '<symbol id="i-' + k + '" viewBox="0 0 24 24">' + re.sub(r'^<svg[^>]*>|</svg>$', '', svg) + '</symbol>'

def icon(name): return f'<svg class="px-icon" shape-rendering="crispEdges" aria-hidden="true" focusable="false"><use href="#i-{name}"/></svg>'
EXT = 'target="_blank" rel="noopener noreferrer"'
e = lambda s: html.escape(s, quote=True)
x_url, tg_url, web_url = e(L['x']), e(L['telegram']), e(L['website'])

# ---- shared social components: X and Telegram are ALWAYS rendered together ----
BUY_SOON = '<span class="soon">SOON</span><span class="sr"> — coming soon</span>'
def socials(variant):
    # Shared look everywhere: X / TWITTER = orange, TELEGRAM = purple, always together.
    xl, tl = 'X / Twitter', 'Telegram'
    if variant == 'hud':      # compact icon pair in the header
        return (f'<span class="socials socials-hud">'
                f'<a class="btn btn-orange btn-sm icon-btn soc-x" href="{x_url}" {EXT} aria-label="HALLOWINU on X / Twitter">{X}</a>'
                f'<a class="btn btn-purple btn-sm icon-btn soc-tg" href="{tg_url}" {EXT} aria-label="HALLOWINU on Telegram">{TG}</a></span>')
    if variant == 'pair':     # full buttons (hero CTA, mobile menu, launch modal)
        return (f'<a class="btn btn-orange soc-btn soc-x" href="{x_url}" {EXT}>{X}{xl}</a>'
                f'<a class="btn btn-purple soc-btn soc-tg" href="{tg_url}" {EXT}>{TG}{tl}</a>')
    if variant == 'terminal': # buy + X + Telegram
        return (f'<nav class="official-links" aria-label="Official HALLOWINU links">'
                f'<button class="btn btn-primary btn-sm" type="button" data-buy>{icon("pumpkin")}Buy{BUY_SOON}</button>'
                f'<a class="btn btn-orange btn-sm soc-x" href="{x_url}" {EXT}>{X}{xl}</a>'
                f'<a class="btn btn-purple btn-sm soc-tg" href="{tg_url}" {EXT}>{TG}{tl}</a></nav>')
    if variant == 'footer':
        return (f'<li><a href="{x_url}" {EXT}>{xl}</a></li>'
                f'<li><a href="{tg_url}" {EXT}>{tl}</a></li>')
    if variant == 'portals':
        return (f'<a class="portal is-x" href="{x_url}" {EXT}><span class="portal-ico">{X}</span>'
                f'<div><h3>X / TWITTER</h3><p>Memes, artwork &amp; updates</p></div><span class="go" aria-hidden="true">›</span></a>'
                f'<a class="portal" href="{tg_url}" {EXT}><span class="portal-ico">{TG}</span>'
                f'<div><h3>TELEGRAM</h3><p>Main lobby · announcements, raids &amp; chat</p></div><span class="go" aria-hidden="true">›</span></a>')
    raise ValueError(variant)

def game_cards():
    out = []
    for i, g in enumerate(site['games']):
        delay = f' data-delay="{i}"' if i else ''
        out.append(
            f'<article class="ax-game px-frame reveal"{delay} data-game="{e(g["id"])}" id="game-{e(g["id"])}">'
            f'<div class="ax-game-art is-{e(g["type"])}"><span class="ico">{icon(g["icon"])}</span></div>'
            f'<h3>{e(g["name"])}</h3><p>{e(g["tagline"])}</p>'
            f'<div class="ax-game-foot"><span class="tag" data-limit>—</span>'
            f'<button class="btn btn-primary btn-sm" type="button" data-play="{e(g["id"])}">{e(g["cta"])}</button></div></article>')
    return '\n          '.join(out)

def spark(seed, trend):
    r = random.Random(seed); pts = []; y = 36; cand = ''
    for i in range(20):
        x = 4 + i * 10
        o = y; y = max(4, min(40, y + r.uniform(-5, 4) - trend))
        hi = min(o, y) - r.uniform(1, 4); lo = max(o, y) + r.uniform(1, 4)
        cls = 'candle' if y <= o else 'candle r'
        cand += f'<rect class="{cls}" x="{x-2}" y="{min(o,y):.1f}" width="4" height="{max(1.5,abs(o-y)):.1f}"/><rect class="{cls}" x="{x-.5}" y="{hi:.1f}" width="1" height="{lo-hi:.1f}"/>'
        pts.append(f'{x},{y:.1f}')
    return f'<svg class="dc-chart" viewBox="0 0 200 44" preserveAspectRatio="none" aria-hidden="true"><g opacity=".55">{cand}</g><polyline class="line" style="--len:260" points="{" ".join(pts)}"/></svg>'

layout = open(P('tools/site/layout.html')).read()
HERO_PRELOAD = '<link rel="preload" href="img/hero-world.webp" as="image" type="image/webp" imagesrcset="img/hero-world-1200.webp 1200w, img/hero-world.webp 2042w" imagesizes="(max-width:700px) 148vw, 100vw">'
PAGES = [
    # (output, content file, url path, title, base for section links, extra)
    ('dist/index.html', 'tools/site/home.html', '/', 'HALLOWINU — The ghost dog of Halloween on Solana', '', HERO_PRELOAD, '', ''),
    ('dist/arcade.html', 'tools/site/arcade.html', '/arcade', 'HALLOWINU Arcade — play, earn points, climb the board', '/', '', ' class="arcade-page"', ' aria-current="true"'),
]
for out, content, path, title, base, preload, mainclass, cur in PAGES:
    t = layout.replace('{{content}}', open(P(content)).read())
    t = t.replace('{{title}}', title).replace('{{path}}', path).replace('{{base}}', base).replace('{{preload}}', preload)
    t = t.replace('{{mainclass}}', mainclass).replace('{{arcadeCurrent}}', cur)
    t = t.replace('{{pagescripts}}', f'<script src="arcade.js?v={V}" defer></script>\n' if 'arcade' in out else '')
    t = t.replace('{{symbols}}', symbols).replace('{{tg}}', TG).replace('{{x}}', X).replace('{{v}}', V)
    t = t.replace('{{spark1}}', spark(3, 1.1)).replace('{{spark2}}', spark(7, 1.4)).replace('{{spark3}}', spark(11, 1.7))
    t = t.replace('{{games}}', game_cards())
    t = re.sub(r'\{\{socials:(\w+)\}\}', lambda m: socials(m.group(1)), t)
    t = re.sub(r'\{\{link:(\w+)\}\}', lambda m: e(L[m.group(1)]), t)
    t = re.sub(r'\{\{icon:(\w+)\}\}', lambda m: icon(m.group(1)), t)
    assert '{{' not in t, (out, re.findall(r'\{\{[^}]+\}\}', t))
    # Guard: every project X link is accompanied by a Telegram link and vice versa.
    assert t.count(L['x']) == t.count(L['telegram']), (out, t.count(L['x']), t.count(L['telegram']))
    open(P(out), 'w').write(t)
    print(out, len(t), 'bytes; x links', t.count(L['x']), 'telegram links', t.count(L['telegram']))

public = {'links': L, 'games': site['games']}
open(P('dist/site-config.js'), 'w').write(
    '/* GENERATED by tools/site/build.py from tools/site/site.json — do not edit by hand. */\n'
    f'window.HALLOWINU_SITE = Object.freeze({json.dumps(public, ensure_ascii=False)});\n')
open(P('worker/site-meta.js'), 'w').write(
    '/* GENERATED by tools/site/build.py from tools/site/site.json — do not edit by hand. */\n'
    f'export const SITE = {json.dumps(public, ensure_ascii=False, indent=2)};\n')
